"""add_money

Revision ID: 87826b6def37
Revises: 2d8bb3d81f97
Create Date: 2023-12-18 19:54:07.758728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87826b6def37'
down_revision: Union[str, None] = '2d8bb3d81f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('money', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'money')
    # ### end Alembic commands ###
